# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190326_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.CharField(max_length=100),
        ),
    ]
